on:
  push:
jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: build
      shell: cmd
      run: |
        cd src/main/native/packr
        call fips
        call fips fetch
        call build-windows-vs2022.bat
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: |
          src\main\native\fips-deploy\packr\packr-win32-vs2022-release\packr.exe
          src\main\native\fips-deploy\packr\packr-win64-vs2022-release\packr.exe
        retention-days: 1
        if-no-files-found: error
  macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        set -e -x
        cd src/main/native/packr
        ./fips
        ./fips fetch
        ./build-macos.sh
    - uses: actions/upload-artifact@v3
      with:
        name: macos
        path: |
          src/main/native/fips-deploy/packr/packr-osx-x64-xcode-release/packr
          src/main/native/fips-deploy/packr/packr-osx-arm64-xcode-release/packr
        retention-days: 1
        if-no-files-found: error
  linux:
    needs: [macos, windows]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - run: sudo apt install -y gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu
    - name: build natives
      run: |
        set -e -x
        cd src/main/native/packr
        ./fips
        ./fips fetch
        ./build-linux.sh
        ./build-linux-aarch64.sh
    - name: build jar
      run: |
        set -e
        cp artifacts/windows/packr-win32-vs2022-release/packr.exe src/main/resources/packr-windows.exe
        cp artifacts/windows/packr-win64-vs2022-release/packr.exe src/main/resources/packr-windows-x64.exe
        cp artifacts/macos/packr-osx-x64-xcode-release/packr src/main/resources/packr-mac-x64
        cp artifacts/macos/packr-osx-arm64-xcode-release/packr src/main/resources/packr-mac-arm64
        mvn clean package
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: |
          src/main/native/fips-deploy/packr/linux-make-release/packr
          src/main/native/fips-deploy/packr/packr-linux-aarch64-make-release/packr
        retention-days: 1
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: jar
        path: target/packr-jar-with-dependencies.jar
        retention-days: 1
        if-no-files-found: error
